config/routes.rb
Rails.application.routes.draw do
  resources :help_requests
  devise_for :users

  resources :code_snippets, only: [ :new, :create, :edit, :update ] do
    member do
      get :preview
    end
  end

  resources :courses do
    resources :lessons, only: [ :new, :create, :show, :edit, :update, :destroy ] do
      resources :comments, only: [ :create, :edit, :update, :destroy ], defaults: { commentable: "Lesson" }
      resources :likes, only: [ :create, :destroy ], defaults: { likeable_type: "Lesson" }
    end
    resources :assignments, only: [ :index, :show, :new, :create, :edit, :update, :destroy ] do
      resources :comments, only: [ :create, :edit, :update, :destroy ], defaults: { commentable: "Assignment" }
      resources :likes, only: [ :create, :destroy ], defaults: { likeable_type: "Assignment" }
    end
  end

  post "courses/:id/join", to: "courses#join", as: :join_course

  # Admin routes
  get "admin/dashboard" => "admin#dashboard"
  get "admin/index" => "admin#index"

  resources :users, only: [ :index, :show, :destroy ] do
    member do
      patch :change_role
    end
  end

  # Define health check route
  get "up" => "rails/health#show", as: :rails_health_check

  # PWA routes
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Static pages routes
  root "static_pages#home"
  get "about" => "static_pages#about"
  get "faq" => "static_pages#faq"
  get "help" => "static_pages#help"
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course

  validates :title, :content, presence: true

  validates :lesson_date, presence: true

  # default_scope { order(lesson_date: :asc) }

  has_many :comments, as: :commentable, dependent: :destroy

  has_many :likes, as: :likeable, dependent: :destroy

  # def comments
  #   Comment.where(commentable: self)
  # end

  # def likes
  #   Like.where(likeable: self)
  # end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
    before_action :authenticate_user!, only: [ :new, :create, :edit, :update ]
    before_action :set_course
    before_action :set_lesson, only: [ :show, :edit, :update ]
    before_action :check_admin, only: [ :new ]

    def show
      @comments = @lesson.comments
      @comment = Comment.new
    end

    def new
        @lesson = @course.lessons.new
    end

    def create
      @lesson = @course.lessons.new(lesson_params)
      if @lesson.save
        redirect_to course_lesson_path(@course, @lesson), notice: "Lesson created successfully."
      else
        render :new
      end
    end

    def edit
        @course = Course.find(params[:course_id])
        @lesson = @course.lessons.find(params[:id])
        render :edit
    end

    def update
      if @lesson.update(lesson_params)
        redirect_to course_lesson_path(@course, @lesson), notice: "Lesson updated successfully."
      else
        render :edit
      end
    end

    private

    def check_admin
      if user_signed_in? && current_user.role != "admin"
       redirect_to root_path, alert: "You are not allowed to visit this page!"
      end
    end

    def set_course
      @course = Course.find(params[:course_id])
    end

    def set_lesson
      @lesson = @course.lessons.find(params[:id])
    end

    def lesson_params
        params.require(:lesson).permit(:title, :content, :lesson_date)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<div class="card-body">
    <%= form_with(model: [@course, @lesson], local: true) do |form| %>
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    <%= form.label :title , class:'form-label fw-bold' %>
                    <%= form.text_field :title, class: "form-control" %>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group">
                    <%= form.label :lesson_date, "Lesson Date" , class:'form-label fw-bold' %>
                    <%= form.datetime_local_field :lesson_date, class: "form-control" %>
                </div>
            </div>
        </div>

         <div class="form-group">
            <%= form.label :content , class:'form-label fw-bold' %>
            <%= form.text_area :content, class: "form-control auto-expand"%>
        </div>

        <div class="form-group my-3">
            <%= form.submit class:"btn btn-success fw-bold" %>
            <%= link_to 'Cancel', course_path(@course), class: "btn btn-secondary" %>
        </div>
    <% end %>
</div>

app/views/lessons/edit.html.erb
<div class="container mt-4">
    <div class="card border-0">
        <div class="card-title text-center my-3 bg-secondary-subtle p-3">
          <h1 class="text-center text-uppercase">  Edit Lesson of <%= @course.title %></h1>
        </div>
       <%= render "form"%>
    </div>
</div>

app/views/lessons/new.html.erb
<div class="container mt-4">
    <div class="card border-0">
        <div class="card-title text-center my-3 bg-secondary-subtle p-3">
          <h1 class="text-center text-uppercase">Create a New Lesson for <%= @course.title %></h1>
        </div>
        <div class="card-body">
            <%= form_with(model: [@course, @lesson], local: true) do |form| %>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <%= form.label :title , class:'form-label fw-bold' %>
                            <%= form.text_field :title, class: "form-control" %>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <%= form.label :lesson_date, "Lesson Date" , class:'form-label fw-bold' %>
                            <%= form.datetime_local_field :lesson_date, class: "form-control" %>
                        </div>
                    </div>
                </div>
        
                 <div class="form-group">
                    <%= form.label :content , class:'form-label fw-bold' %>
                    <%= form.text_area :content, class: "form-control", rows: 5 %>
                </div>
        
                <div class="form-group my-3">
                    <%= form.submit "Create Lesson", class: "btn btn-success fw-bold" %>
                    <%= link_to 'Cancel', course_path(@course), class: "btn btn-secondary" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/lessons/show.html.erb
<div class="container mt-4">
  <div class="card border-0">
    <div class="card-title text-center my-3 bg-secondary-subtle p-3">
      <h1 class="text-center text-uppercase"><%= @lesson.title %></h1>
    </div>
    <div class="card-body">
      <p class="lead"><%= @lesson.content %></p>
      <div class="d-flex align-items-center justify-content-between">
        <h3 class="mt-4 mb-3"> <%= @comments.count %> Comments</h3>
        <div class="d-flex align-items-center bg-primary rounded-pill">
          <%= button_to course_lesson_likes_path(@course, @lesson, like_type: 1, likeable_type: "Lesson"), method: :post, class: "btn text-white fs-4" do %>
              <i class="fa-solid fa-thumbs-up"></i>
              <span><%= @like_count %></span>
          <% end %>
          <span class="fs-4 text-white"> | </span>
          <%= button_to course_lesson_likes_path(@course, @lesson, like_type: 2, likeable_type: "Lesson"), method: :post, class: "btn text-white fs-4" do %>
            <i class="fa-solid fa-thumbs-down"></i>
            <span><%= @dislike_count %></span>
          <% end %>
        </div>
      </div>
      <%= render 'comments/form' ,commentable: @lesson %>
      <div class="py-3 px-3">
        <%= render 'comments/comment', comments: @comments, commentable: @lesson %>
      </div>
    </div>
  </div>
</div>